version: '3.8'

services:
  librenms:
    image: librenms/librenms:latest
    hostname: librenms
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "7000:8000"
    environment:
      - TZ=UTC
      - PUID=1000
      - PGID=1000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=librenms
      - DB_USER=librenms
      - DB_PASSWORD=secure_librenms_password_change_me
      - DB_TIMEOUT=60
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - BASE_URL=http://localhost:7000
      - POLLERS=16
      - CRON_FPING=true
      - CRON_DISCOVERY_ENABLE=true
      - CRON_DAILY_ENABLE=true
      - CRON_ALERTS_ENABLE=true
      - CRON_BILLING_ENABLE=true
      - CRON_BILLING_CALCULATE_ENABLE=true
      - CRON_CHECK_SERVICES_ENABLE=true
      - CRON_POLLER_ENABLE=true
      - CRON_DISCOVERY_NEW_ENABLE=true
    volumes:
      - librenms_data:/data
      - librenms_logs:/opt/librenms/logs
      - librenms_rrd:/opt/librenms/rrd
      - librenms_storage:/opt/librenms/storage
    depends_on:
      - db
      - redis
    networks:
      - librenms_net

  db:
    image: postgres:15-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - POSTGRES_DB=librenms
      - POSTGRES_USER=librenms
      - POSTGRES_PASSWORD=secure_librenms_password_change_me
      - TZ=UTC
    volumes:
      - librenms_postgres:/var/lib/postgresql/data
    networks:
      - librenms_net

  redis:
    image: redis:7-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - TZ=UTC
    networks:
      - librenms_net

  dispatcher:
    image: librenms/librenms:latest
    hostname: librenms-dispatcher
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - TZ=UTC
      - PUID=1000
      - PGID=1000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=librenms
      - DB_USER=librenms
      - DB_PASSWORD=secure_librenms_password_change_me
      - DB_TIMEOUT=60
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - DISPATCHER_NODE_ID=dispatcher1
      - SIDECAR_DISPATCHER=1
    volumes:
      - librenms_data:/data
      - librenms_logs:/opt/librenms/logs
      - librenms_rrd:/opt/librenms/rrd
      - librenms_storage:/opt/librenms/storage
    depends_on:
      - librenms
      - redis
    networks:
      - librenms_net

  syslogng:
    image: librenms/librenms:latest
    hostname: librenms-syslogng
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "514:514/udp"
      - "514:514/tcp"
    environment:
      - TZ=UTC
      - PUID=1000
      - PGID=1000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=librenms
      - DB_USER=librenms
      - DB_PASSWORD=secure_librenms_password_change_me
      - DB_TIMEOUT=60
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - SIDECAR_SYSLOGNG=1
    volumes:
      - librenms_data:/data
      - librenms_logs:/opt/librenms/logs
      - librenms_syslog:/opt/librenms/syslog
    depends_on:
      - librenms
      - redis
    networks:
      - librenms_net

  snmptrapd:
    image: librenms/librenms:latest
    hostname: librenms-snmptrapd
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "162:162/udp"
    environment:
      - TZ=UTC
      - PUID=1000
      - PGID=1000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=librenms
      - DB_USER=librenms
      - DB_PASSWORD=secure_librenms_password_change_me
      - DB_TIMEOUT=60
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - SIDECAR_SNMPTRAPD=1
    volumes:
      - librenms_data:/data
      - librenms_logs:/opt/librenms/logs
    depends_on:
      - librenms
      - redis
    networks:
      - librenms_net

networks:
  librenms_net:
    driver: overlay
    attachable: true

volumes:
  librenms_data:
  librenms_logs:
  librenms_rrd:
  librenms_storage:
  librenms_postgres:
  librenms_syslog: