version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: test_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=librenms
      - POSTGRES_USER=librenms
      - POSTGRES_PASSWORD=testpass123
      - TZ=UTC
    ports:
      - "5432:5432"

networks:
  default:
    driver: bridge
